/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.*;
/*
 * Display.java
 *
 * Created on Sep 12, 2015, 9:07:00 AM
 */

/**
 *
 * @author Guest
 */
public class Display extends javax.swing.JFrame {

    /** Creates new form Display */
    public Display() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        R1 = new javax.swing.JRadioButton();
        R2 = new javax.swing.JRadioButton();
        R3 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tb1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        L = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Show Products - easyShopping.com");
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "AVAILABLE SHOPPING WEBSITES", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Copperplate Gothic Bold", 1, 18), new java.awt.Color(255, 0, 0))); // NOI18N

        buttonGroup1.add(R1);
        R1.setFont(new java.awt.Font("Bodoni MT Black", 1, 12)); // NOI18N
        R1.setForeground(new java.awt.Color(0, 0, 153));
        R1.setText("AMAZON.COM");
        R1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(R2);
        R2.setFont(new java.awt.Font("Bodoni MT Black", 1, 12)); // NOI18N
        R2.setForeground(new java.awt.Color(0, 0, 255));
        R2.setText("FLIPKART.COM");
        R2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(R3);
        R3.setFont(new java.awt.Font("Bodoni MT Black", 1, 12)); // NOI18N
        R3.setForeground(new java.awt.Color(255, 0, 0));
        R3.setText("SNAPDEAL.COM");
        R3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(R1)
                .addGap(95, 95, 95)
                .addComponent(R2)
                .addGap(95, 95, 95)
                .addComponent(R3)
                .addGap(95, 95, 95))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(R2)
                .addComponent(R1)
                .addComponent(R3))
        );

        Tb1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product_ID", "Product_Name", "Brand", "MRP", "Price_Offered", "Delivery_Time", "Mode_Of_Payment"
            }
        ));
        jScrollPane1.setViewportView(Tb1);

        jButton1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 153));
        jButton1.setText("Retrieve Products");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jButton2.setText("Back To Main Menu");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Castellar", 1, 48)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 51, 102));
        jLabel23.setText("EasyShopping.com");

        L.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 1, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(jButton1)
                        .addGap(175, 175, 175)
                        .addComponent(jButton2)
                        .addGap(175, 175, 175)))
                .addGap(110, 110, 110))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addGap(236, 236, 236))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(L, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(349, 349, 349))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23)
                .addGap(2, 2, 2)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(L, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void R1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R1ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model=(DefaultTableModel)Tb1.getModel();
         model.setRowCount(0);
         L.setText("");
    }//GEN-LAST:event_R1ActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
        DefaultTableModel model=(DefaultTableModel)Tb1.getModel();
         model.setRowCount(0);
         L.setText("");
    }//GEN-LAST:event_formWindowGainedFocus

    private void R2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R2ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model=(DefaultTableModel)Tb1.getModel();
         model.setRowCount(0);
         L.setText("");
    }//GEN-LAST:event_R2ActionPerformed

    private void R3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R3ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model=(DefaultTableModel)Tb1.getModel();
         model.setRowCount(0);
         L.setText("");
    }//GEN-LAST:event_R3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Menu m=new Menu();
        m.setVisible(true);
            this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(R1.isSelected())
        {    
           DefaultTableModel modelAmazon=(DefaultTableModel)Tb1.getModel();
        try
        {Class.forName("com.mysql.jdbc.Driver");

        Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/online","root","password");
        Statement S=con.createStatement();
        ResultSet R=S.executeQuery("select * from amazon;");
        while(R.next())
        {String PID=R.getString("Product_ID");
         String PN=R.getString("Product_Name");
         String B=R.getString("Brand");
         int MRP=R.getInt("MRP");
         int PO=R.getInt("Price_Offered");
         int DT=R.getInt("Delivery_Time");
         String MOP=R.getString("Mode_Of_Payment");
         modelAmazon.addRow(new Object[]{PID,PN,B,MRP,PO,DT,MOP});
        }
        R.close();
        S.close();
        con.close();
        L.setText("AMAZON.COM"); 
        }
        catch(Exception E)
     {JOptionPane.showMessageDialog(null,"Error in connection");
        }
        }
          if(R2.isSelected())
        {
           DefaultTableModel modelFlipkart=(DefaultTableModel)Tb1.getModel();
        try
        {Class.forName("com.mysql.jdbc.Driver");

        Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/online","root","password");
        Statement S=con.createStatement();
        ResultSet R=S.executeQuery("select * from flipkart;");
        while(R.next())
        {String PID=R.getString("Product_ID");
         String PN=R.getString("Product_Name");
         String B=R.getString("Brand");
         int MRP=R.getInt("MRP");
         int PO=R.getInt("Price_Offered");
         int DT=R.getInt("Delivery_Time");
         String MOP=R.getString("Mode_Of_Payment");
         modelFlipkart.addRow(new Object[]{PID,PN,B,MRP,PO,DT,MOP});
        }
        R.close();
        S.close();
        con.close();
        L.setText("FLIPKART.COM"); 
        }
        catch(Exception E)
     {JOptionPane.showMessageDialog(null,"Error in connection");
        }
        }
          if(R3.isSelected())
        {
           DefaultTableModel modelSnapdeal=(DefaultTableModel)Tb1.getModel();
        try
        {Class.forName("com.mysql.jdbc.Driver");

        Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/online","root","password");
        Statement S=con.createStatement();
        ResultSet R=S.executeQuery("select * from snapdeal;");
        while(R.next())
        {String PID=R.getString("Product_ID");
         String PN=R.getString("Product_Name");
         String B=R.getString("Brand");
         int MRP=R.getInt("MRP");
         int PO=R.getInt("Price_Offered");
         int DT=R.getInt("Delivery_Time");
         String MOP=R.getString("Mode_Of_Payment");
         modelSnapdeal.addRow(new Object[]{PID,PN,B,MRP,PO,DT,MOP});
        }
        R.close();
        S.close();
        con.close();
        L.setText("SNAPDEAL.COM"); 
        }
        catch(Exception E)
     {JOptionPane.showMessageDialog(null,"Error in connection");
        }
        }
    
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Display().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel L;
    private javax.swing.JRadioButton R1;
    private javax.swing.JRadioButton R2;
    private javax.swing.JRadioButton R3;
    private javax.swing.JTable Tb1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
